### ISSUE TITLE
Rhel8 Vendor 8.1 vs 8.10

### ISSUE THREAD

**Issue by jrmetzger** [mitre/redhat-enterprise-linux-8-stig-baseline#28]
https://github.com/mitre/redhat-enterprise-linux-8-stig-baseline/blob/33e03624df557e7c2186d25e557f5f4a39f2cbd5/controls/SV-230221.rb#L63

Latest (current) version of rhel8 (8.10) conflicts when comparing to version 8.1 and fails. Probably just grabs the '8.1' in both strings and picks the first of the 2. Needs investigating

**Comment by karikarshivani** [comment]
Seems to be logged in #27 so closing this for now. Thanks for raising the issue!
